name: .NET

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    # Dataverse.Api.Abstractions.EntityDelete
    
    - name: Restore Dataverse.Api.Abstractions.EntityDelete
      run: dotnet restore ./src/*/Dataverse.Api.Abstractions.EntityDelete.csproj

    - name: Build Dataverse.Api.Abstractions.EntityDelete
      run: dotnet build ./src/*/Dataverse.Api.Abstractions.EntityDelete.csproj --no-restore  -c Release

    - name: Pack Dataverse.Api.Abstractions.EntityDelete
      run: dotnet pack ./src/*/Dataverse.Api.Abstractions.EntityDelete.csproj --no-restore -o ~/nuget  -c Release

    # Dataverse.Api.Abstractions.EntityCreate
    
    - name: Restore Dataverse.Api.Abstractions.EntityCreate
      run: dotnet restore ./src/*/Dataverse.Api.Abstractions.EntityCreate.csproj

    - name: Build Dataverse.Api.Abstractions.EntityCreate
      run: dotnet build ./src/*/Dataverse.Api.Abstractions.EntityCreate.csproj --no-restore  -c Release

    - name: Pack Dataverse.Api.Abstractions.EntityCreate
      run: dotnet pack ./src/*/Dataverse.Api.Abstractions.EntityCreate.csproj --no-restore -o ~/nuget  -c Release

    # Dataverse.Api.Abstractions.EntitySetGet
    
    - name: Restore Dataverse.Api.Abstractions.EntitySetGet
      run: dotnet restore ./src/*/Dataverse.Api.Abstractions.EntitySetGet.csproj

    - name: Build Dataverse.Api.Abstractions.EntitySetGet
      run: dotnet build ./src/*/Dataverse.Api.Abstractions.EntitySetGet.csproj --no-restore  -c Release

    - name: Pack Dataverse.Api.Abstractions.EntitySetGet
      run: dotnet pack ./src/*/Dataverse.Api.Abstractions.EntitySetGet.csproj --no-restore -o ~/nuget  -c Release
      
    # Dataverse.Api.Abstractions.EntityGet
    
    - name: Restore Dataverse.Api.Abstractions.EntityGet
      run: dotnet restore ./src/*/Dataverse.Api.Abstractions.EntityGet.csproj

    - name: Build Dataverse.Api.Abstractions.EntityGet
      run: dotnet build ./src/*/Dataverse.Api.Abstractions.EntityGet.csproj --no-restore  -c Release

    - name: Pack Dataverse.Api.Abstractions.EntityGet
      run: dotnet pack ./src/*/Dataverse.Api.Abstractions.EntityGet.csproj --no-restore -o ~/nuget  -c Release

    # Dataverse.Api.Abstractions
    
    - name: Restore Dataverse.Api.Abstractions
      run: dotnet restore ./src/*/Dataverse.Api.Abstractions.csproj

    - name: Build Dataverse.Api.Abstractions
      run: dotnet build ./src/*/Dataverse.Api.Abstractions.csproj --no-restore  -c Release

    - name: Pack Dataverse.Api.Abstractions
      run: dotnet pack ./src/*/Dataverse.Api.Abstractions.csproj --no-restore -o ~/nuget  -c Release
      
    # Dataverse.Api

    - name: Restore Dataverse.Api
      run: dotnet restore ./src/*/Dataverse.Api.csproj

    - name: Build Dataverse.Api
      run: dotnet build ./src/*/Dataverse.Api.csproj --no-restore  -c Release

    - name: Pack Dataverse.Api
      run: dotnet pack ./src/*/Dataverse.Api.csproj --no-restore -o ~/nuget  -c Release
      
    # Push
      
    - name: Push Packages
      if: ${{ github.event_name == 'push' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -k ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --skip-duplicate
