name: .NET

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    - name: Restore Dataverse.Api.Abstractions
      run: dotnet restore ./src/Dataverse.Api.Abstractions/Dataverse.Api.Abstractions.csproj

    - name: Build Dataverse.Api.Abstractions
      run: dotnet build ./src/Dataverse.Api.Abstractions/Dataverse.Api.Abstractions.csproj --no-restore

    - name: Pack Dataverse.Api.Abstractions
      run: dotnet pack ./src/Dataverse.Api.Abstractions/Dataverse.Api.Abstractions.csproj --no-restore -o ~/nuget

    - name: Restore Dataverse.Api
      run: dotnet restore ./src/Dataverse.Api/Dataverse.Api.csproj

    - name: Build Dataverse.Api
      run: dotnet build ./src/Dataverse.Api/Dataverse.Api.csproj --no-restore

    - name: Pack Dataverse.Api
      run: dotnet pack ./src/Dataverse.Api/Dataverse.Api.csproj --no-restore -o ~/nuget
      
    - name: Push Packages
      if: ${{ github.event_name == 'push' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -k ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --skip-duplicate
